/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as TryRouteImport } from './routes/try'
import { Route as PProjectIdRouteImport } from './routes/p.$projectId'
import { Route as PProjectIdIndexRouteImport } from './routes/p.$projectId.index'
import { Route as PProjectIdKnitRouteImport } from './routes/p.$projectId.knit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const TryRoute = TryRouteImport.update({
  id: '/try',
  path: '/try',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectIdRoute = PProjectIdRouteImport.update({
  id: '/p/$projectId',
  path: '/p/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectIdIndexRoute = PProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PProjectIdRoute,
} as any)
const PProjectIdKnitRoute = PProjectIdKnitRouteImport.update({
  id: '/knit',
  path: '/knit',
  getParentRoute: () => PProjectIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/try': typeof TryRoute
  '/p/$projectId': typeof PProjectIdRouteWithChildren
  '/p/$projectId/knit': typeof PProjectIdKnitRoute
  '/p/$projectId/': typeof PProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/try': typeof TryRoute
  '/p/$projectId/knit': typeof PProjectIdKnitRoute
  '/p/$projectId': typeof PProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/try': typeof TryRoute
  '/p/$projectId': typeof PProjectIdRouteWithChildren
  '/p/$projectId/knit': typeof PProjectIdKnitRoute
  '/p/$projectId/': typeof PProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reset-password'
    | '/sign-in'
    | '/try'
    | '/p/$projectId'
    | '/p/$projectId/knit'
    | '/p/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reset-password'
    | '/sign-in'
    | '/try'
    | '/p/$projectId/knit'
    | '/p/$projectId'
  id:
    | '__root__'
    | '/'
    | '/reset-password'
    | '/sign-in'
    | '/try'
    | '/p/$projectId'
    | '/p/$projectId/knit'
    | '/p/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  TryRoute: typeof TryRoute
  PProjectIdRoute: typeof PProjectIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/try': {
      id: '/try'
      path: '/try'
      fullPath: '/try'
      preLoaderRoute: typeof TryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$projectId': {
      id: '/p/$projectId'
      path: '/p/$projectId'
      fullPath: '/p/$projectId'
      preLoaderRoute: typeof PProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$projectId/': {
      id: '/p/$projectId/'
      path: '/'
      fullPath: '/p/$projectId/'
      preLoaderRoute: typeof PProjectIdIndexRouteImport
      parentRoute: typeof PProjectIdRoute
    }
    '/p/$projectId/knit': {
      id: '/p/$projectId/knit'
      path: '/knit'
      fullPath: '/p/$projectId/knit'
      preLoaderRoute: typeof PProjectIdKnitRouteImport
      parentRoute: typeof PProjectIdRoute
    }
  }
}

interface PProjectIdRouteChildren {
  PProjectIdKnitRoute: typeof PProjectIdKnitRoute
  PProjectIdIndexRoute: typeof PProjectIdIndexRoute
}

const PProjectIdRouteChildren: PProjectIdRouteChildren = {
  PProjectIdKnitRoute: PProjectIdKnitRoute,
  PProjectIdIndexRoute: PProjectIdIndexRoute,
}

const PProjectIdRouteWithChildren = PProjectIdRoute._addFileChildren(
  PProjectIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  TryRoute: TryRoute,
  PProjectIdRoute: PProjectIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
